print("Program starting.")
print()
color = input("Insert a hex color: ")
print()
print("Colors")
print(f"- Red {color[1:3]}")
print(f"- Green {color[3:5]}")
print(f"- Blue {color[5:7]}")
print()
print("Program ending.")

